# This is a basic workflow to help you get started with Actions

name: widoco

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Java
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Compile documentation
      run: |
        cd widoco && ./generate.sh && cd ..
        mv widoco/output/roh/index-en.html widoco/output/roh/index.html
        mv widoco/output/rohes/index-en.html widoco/output/rohes/index.html
        mv widoco/output/rohum/index-en.html widoco/output/rohum/index.html   
        mv unesco-individuals.rdf widoco/output/roh/unesco-individuals.rdf  
        mv roh-v2.owl widoco/output/roh/ontology.rdf  
        mv rohes-v2.owl widoco/output/rohes/ontology.rdf  
        mv rohum.owl widoco/output/rohum/ontology.rdf  
        mkdir widoco/output/data
        mv examples/data.ttl widoco/output/data/data.ttl

    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        keep_history: true 
        build_dir: widoco/output 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
